### ISSUE TITLE
Extension fails

### ISSUE THREAD

**Issue by dustincatap** [cross-solutions/install-flutter-sdk#13]
Output:

```
Error: Cannot find module 'azure-pipelines-task-lib/task'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\a\_tasks\install-flutter-sdk_7248c5a0-bfab-4da2-85ca-95230bf93a24\0.2.6\index.js:38:12)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
```

Already published 0.2.9 for the fix, but it seems that Azure DevOps is not using the latest version.

**Comment by PopovVA** [comment]
Hey. Ok, I'll try to fix it

**Comment by PopovVA** [comment]
@dustincatap Hey, why the version is 1.0.0 in the azure devops marketplace?
<img width="816" alt="Screenshot 2021-06-03 at 13 11 06" src="https://user-images.githubusercontent.com/24640217/120628326-3d11fb00-c46d-11eb-94af-688fdf57ab10.png">

**Comment by rodydavis** [comment]
```
##[error]404 - "<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist.</Message></Error>"
```
